"""initial schema

Revision ID: ded68be4ad49
Revises: 
Create Date: 2026-09-01 15:04:10.148763

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ded68be4ad49'
down_revision: Union[str, None] = None
branch_labels: Union[Sequence[str], None] = None
depends_on: Union[Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anki_export_batches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('format', sa.String(length=16), nullable=False),
    sa.Column('filter_from', sa.String(length=10), nullable=True),
    sa.Column('filter_to', sa.String(length=10), nullable=True),
    sa.Column('include_all', sa.Boolean(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('import_batches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('update_id', sa.String(length=36), nullable=False),
    sa.Column('schema_version', sa.String(length=16), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_json', sa.Text(), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('result_summary', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash'),
    sa.UniqueConstraint('update_id')
    )
    op.create_table('learner_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('native_language', sa.String(length=64), nullable=False),
    sa.Column('current_level', sa.String(length=8), nullable=False),
    sa.Column('target_level', sa.String(length=8), nullable=False),
    sa.Column('english_variety', sa.String(length=64), nullable=False),
    sa.Column('pronunciation_standard', sa.String(length=64), nullable=False),
    sa.Column('daily_study_minutes', sa.Integer(), nullable=False),
    sa.Column('persian_meaning_policy', sa.Text(), nullable=False),
    sa.Column('professional_background', sa.JSON(), nullable=False),
    sa.Column('learning_goals', sa.JSON(), nullable=False),
    sa.Column('default_timezone', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_learner_profile_singleton'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('normalized_tag', sa.String(length=128), nullable=False),
    sa.Column('display_tag', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_tag')
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('local_session_date', sa.String(length=10), nullable=False),
    sa.Column('topic', sa.String(length=256), nullable=False),
    sa.Column('session_type', sa.String(length=64), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('strengths', sa.JSON(), nullable=False),
    sa.Column('weak_points', sa.JSON(), nullable=False),
    sa.Column('next_focus', sa.JSON(), nullable=False),
    sa.Column('fluency_notes', sa.JSON(), nullable=False),
    sa.Column('source_import_batch_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_import_batch_id'], ['import_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('learning_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('dedup_key', sa.String(length=512), nullable=False),
    sa.Column('display_text', sa.String(length=512), nullable=False),
    sa.Column('cefr_level', sa.String(length=8), nullable=True),
    sa.Column('importance_score', sa.Integer(), nullable=False),
    sa.Column('mastery_score', sa.Integer(), nullable=False),
    sa.Column('mastery_status', sa.String(length=16), nullable=False),
    sa.Column('manual_mastery_override', sa.String(length=16), nullable=True),
    sa.Column('usage_count_total', sa.Integer(), nullable=False),
    sa.Column('usage_count_correct', sa.Integer(), nullable=False),
    sa.Column('first_learned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_session_id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("kind in ('vocabulary','expression','grammar','mistake')", name='ck_learning_items_kind'),
    sa.CheckConstraint('importance_score >= 1 AND importance_score <= 10', name='ck_learning_items_importance'),
    sa.CheckConstraint('mastery_score >= 0 AND mastery_score <= 100', name='ck_learning_items_mastery'),
    sa.ForeignKeyConstraint(['source_session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'dedup_key', name='uq_learning_items_kind_dedup_key')
    )
    op.create_table('memory_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('current_topics', sa.JSON(), nullable=False),
    sa.Column('active_goals', sa.JSON(), nullable=False),
    sa.Column('weak_points', sa.JSON(), nullable=False),
    sa.Column('completed_topics', sa.JSON(), nullable=False),
    sa.Column('next_session_focus', sa.JSON(), nullable=False),
    sa.Column('last_session_id', sa.String(length=36), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_memory_state_singleton'),
    sa.ForeignKeyConstraint(['last_session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anki_export_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('export_batch_id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('item_revision', sa.Integer(), nullable=False),
    sa.Column('exported_content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['export_batch_id'], ['anki_export_batches.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['learning_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expression_details',
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('expression_text', sa.String(length=512), nullable=False),
    sa.Column('expression_type', sa.String(length=32), nullable=False),
    sa.Column('meaning_english', sa.Text(), nullable=False),
    sa.Column('meaning_persian', sa.Text(), nullable=True),
    sa.Column('ipa_american', sa.String(length=256), nullable=True),
    sa.Column('usage_contexts', sa.JSON(), nullable=False),
    sa.Column('common_errors', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['learning_items.id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('grammar_details',
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('pattern_name', sa.String(length=256), nullable=False),
    sa.Column('explanation_english', sa.Text(), nullable=False),
    sa.Column('explanation_persian', sa.Text(), nullable=True),
    sa.Column('structure', sa.Text(), nullable=False),
    sa.Column('learner_problem', sa.Text(), nullable=False),
    sa.Column('common_errors', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['learning_items.id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('item_examples',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('sentence', sa.Text(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('source_session_id', sa.String(length=36), nullable=True),
    sa.Column('normalized_sentence', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['learning_items.id'], ),
    sa.ForeignKeyConstraint(['source_session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'normalized_sentence', name='uq_item_examples_norm')
    )
    op.create_table('item_revisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('before_json', sa.JSON(), nullable=True),
    sa.Column('after_json', sa.JSON(), nullable=False),
    sa.Column('change_source', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['learning_items.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_tags',
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['learning_items.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('item_id', 'tag_id')
    )
    op.create_table('mistake_details',
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('wrong_sentence', sa.Text(), nullable=False),
    sa.Column('corrected_sentence', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('explanation_english', sa.Text(), nullable=False),
    sa.Column('explanation_persian', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['learning_items.id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('usage_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('correctness', sa.Boolean(), nullable=True),
    sa.Column('evidence_context', sa.Text(), nullable=False),
    sa.Column('correction', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('import_batch_id', sa.String(length=36), nullable=True),
    sa.CheckConstraint("event_type in ('user_production','prompted_recall','coach_introduction','mistake_occurrence')", name='ck_usage_events_type'),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['learning_items.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vocabulary_details',
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('word', sa.String(length=256), nullable=False),
    sa.Column('lemma', sa.String(length=256), nullable=False),
    sa.Column('part_of_speech', sa.String(length=32), nullable=False),
    sa.Column('sense_key', sa.String(length=128), nullable=False),
    sa.Column('meaning_english', sa.Text(), nullable=False),
    sa.Column('meaning_persian', sa.Text(), nullable=True),
    sa.Column('ipa_american', sa.String(length=256), nullable=True),
    sa.Column('stress_note', sa.String(length=256), nullable=True),
    sa.Column('usage_note', sa.Text(), nullable=True),
    sa.Column('collocations', sa.JSON(), nullable=False),
    sa.Column('common_errors', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['learning_items.id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vocabulary_details')
    op.drop_table('usage_events')
    op.drop_table('mistake_details')
    op.drop_table('item_tags')
    op.drop_table('item_revisions')
    op.drop_table('item_examples')
    op.drop_table('grammar_details')
    op.drop_table('expression_details')
    op.drop_table('anki_export_items')
    op.drop_table('memory_state')
    op.drop_table('learning_items')
    op.drop_table('sessions')
    op.drop_table('tags')
    op.drop_table('learner_profile')
    op.drop_table('import_batches')
    op.drop_table('anki_export_batches')
    # ### end Alembic commands ###
